# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-12 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name=b'T\xc3\xadtulo')),
                ('description', models.TextField(verbose_name=b'Descri\xc3\xa7\xc3\xa3o')),
                ('quantity', models.IntegerField(verbose_name=b'Quantidade')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name=b'Pre\xc3\xa7o')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name=b'Desconto')),
                ('photo', models.ImageField(max_length=255, upload_to=product.models.upload_to_photo, verbose_name='Foto')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name=b'Data')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
